# Generated by Django 4.2.8 on 2023-12-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_first_name_account_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.sex', verbose_name='Пол'),
        ),
    ]
