# Generated by Django 4.2.8 on 2024-01-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_first_name_alter_account_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sex',
            name='identifier',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sex',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
