# Generated by Django 4.2.8 on 2023-12-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_cat_members_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='is_published',
        ),
    ]
