# Generated by Django 4.2.8 on 2023-12-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_members_is_published'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Member',
        ),
    ]
