# Generated by Django 4.2.8 on 2023-12-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_userprofile_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='time_update',
        ),
    ]
