# Generated by Django 4.2.8 on 2023-12-16 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_remove_userprofile_email_remove_userprofile_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='header',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='contacts',
            old_name='header',
            new_name='title',
        ),
    ]
