# Generated by Django 4.2.8 on 2023-12-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_usermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Sex',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='category',
            new_name='sex',
        ),
    ]
