# Generated by Django 4.2.8 on 2023-12-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_rename_category_sex_rename_category_userprofile_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
